export const users = [
  {
    fullname: "John Doe",
    email: "john.doe@example.com",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    fullname: "Jane Smith",
    email: "jane.smith@example.com",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    fullname: "Alice Johnson",
    email: "alice.johnson@example.com",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    fullname: "Bob Brown",
    email: "bob.brown@example.com",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    fullname: "Charlie Davis",
    email: "charlie.davis@example.com",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    fullname: "Diana Evans",
    email: "diana.evans@example.com",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    fullname: "Ethan Harris",
    email: "ethan.harris@example.com",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    fullname: "Fiona Green",
    email: "fiona.green@example.com",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    fullname: "George Hill",
    email: "george.hill@example.com",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    fullname: "Hannah Scott",
    email: "hannah.scott@example.com",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    fullname: "Ian Moore",
    email: "ian.moore@example.com",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    fullname: "Jasmine Lewis",
    email: "jasmine.lewis@example.com",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    fullname: "Kyle Walker",
    email: "kyle.walker@example.com",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    fullname: "Laura Hall",
    email: "laura.hall@example.com",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    fullname: "Michael Young",
    email: "michael.young@example.com",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    fullname: "Nina Clark",
    email: "nina.clark@example.com",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    fullname: "Oscar King",
    email: "oscar.king@example.com",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    fullname: "Paula Martinez",
    email: "paula.martinez@example.com",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    fullname: "Quinn Lee",
    email: "quinn.lee@example.com",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    fullname: "Rachel Turner",
    email: "rachel.turner@example.com",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    fullname: "Sam Wilson",
    email: "sam.wilson@example.com",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    fullname: "Tina Perez",
    email: "tina.perez@example.com",
    image: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    fullname: "Umar Murphy",
    email: "umar.murphy@example.com",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    fullname: "Vera Baker",
    email: "vera.baker@example.com",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    fullname: "Will Harris",
    email: "will.harris@example.com",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    fullname: "Xena Reed",
    email: "xena.reed@example.com",
    image: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    fullname: "Yusuf Anderson",
    email: "yusuf.anderson@example.com",
    image: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    fullname: "Zara Mitchell",
    email: "zara.mitchell@example.com",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    fullname: "Adam Carter",
    email: "adam.carter@example.com",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    fullname: "Bella Adams",
    email: "bella.adams@example.com",
    image: "https://randomuser.me/api/portraits/women/15.jpg",
  },
];

export const dummyUsers = [
  { id: "user1_id", name: "Alice" },
  { id: "user2_id", name: "Bob" },
  { id: "user3_id", name: "Charlie" },
  { id: "user4_id", name: "Diana" },
];

export const singleChat = {
  id: "chat1_id",
  name: null, // Not needed for a single conversation
  isGroup: false,
  createdAt: new Date("2024-08-15T09:00:00Z"),
  updatedAt: new Date("2024-08-15T09:30:00Z"),
  messages: [
    {
      id: "msg1_id",
      content: "Hey Bob, how's it going?",
      senderId: "user1_id",
      chatId: "chat1_id",
      createdAt: new Date("2024-08-15T09:10:00Z"),
      updatedAt: new Date("2024-08-15T09:10:00Z"),
    },
    {
      id: "msg2_id",
      content: "I'm good, Alice! How about you?",
      senderId: "user2_id",
      chatId: "chat1_id",
      createdAt: new Date("2024-08-15T09:12:00Z"),
      updatedAt: new Date("2024-08-15T09:12:00Z"),
    },
    {
      id: "msg3_id",
      content: "Doing well, just getting started with work.",
      senderId: "user1_id",
      chatId: "chat1_id",
      createdAt: new Date("2024-08-15T09:15:00Z"),
      updatedAt: new Date("2024-08-15T09:15:00Z"),
    },
  ],
  participants: [
    { id: "user1_id", name: "Alice" },
    { id: "user2_id", name: "Bob" },
  ],
};
export const groupChat = {
  id: "chat2_id",
  name: "Project Team",
  isGroup: true,
  createdAt: new Date("2024-08-15T08:00:00Z"),
  updatedAt: new Date("2024-08-15T09:30:00Z"),
  messages: [
    {
      id: "msg1_id",
      content: "Good morning, team!",
      senderId: "user3_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:05:00Z"),
      updatedAt: new Date("2024-08-15T08:05:00Z"),
    },
    {
      id: "msg2_id",
      content: "Morning Charlie!",
      senderId: "user1_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:07:00Z"),
      updatedAt: new Date("2024-08-15T08:07:00Z"),
    },
    {
      id: "msg3_id",
      content: "Hey everyone, let's discuss the project status.",
      senderId: "user4_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:10:00Z"),
      updatedAt: new Date("2024-08-15T08:10:00Z"),
    },
    {
      id: "msg4_id",
      content: "Sure, I have completed my part.",
      senderId: "user2_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:12:00Z"),
      updatedAt: new Date("2024-08-15T08:12:00Z"),
    },
    {
      id: "msg5_id",
      content: "Great! Let's sync up later today.",
      senderId: "user3_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:15:00Z"),
      updatedAt: new Date("2024-08-15T08:15:00Z"),
    },
    {
      id: "msg6_id",
      content: "Can we have a quick call at 3 PM?",
      senderId: "user1_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:20:00Z"),
      updatedAt: new Date("2024-08-15T08:20:00Z"),
    },
    {
      id: "msg7_id",
      content: "I'm available at 3 PM.",
      senderId: "user4_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:22:00Z"),
      updatedAt: new Date("2024-08-15T08:22:00Z"),
    },
    {
      id: "msg8_id",
      content: "Same here.",
      senderId: "user2_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:23:00Z"),
      updatedAt: new Date("2024-08-15T08:23:00Z"),
    },
    {
      id: "msg9_id",
      content: "I'll send a calendar invite for the call.",
      senderId: "user1_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:25:00Z"),
      updatedAt: new Date("2024-08-15T08:25:00Z"),
    },
    {
      id: "msg10_id",
      content: "Thanks, Alice!",
      senderId: "user3_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:26:00Z"),
      updatedAt: new Date("2024-08-15T08:26:00Z"),
    },
    {
      id: "msg11_id",
      content: "No problem!",
      senderId: "user1_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:28:00Z"),
      updatedAt: new Date("2024-08-15T08:28:00Z"),
    },
    {
      id: "msg12_id",
      content: "By the way, did anyone review the latest design mockups?",
      senderId: "user4_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:30:00Z"),
      updatedAt: new Date("2024-08-15T08:30:00Z"),
    },
    {
      id: "msg13_id",
      content:
        "I took a quick look. They look solid, but we might need to adjust the color scheme.",
      senderId: "user2_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:35:00Z"),
      updatedAt: new Date("2024-08-15T08:35:00Z"),
    },
    {
      id: "msg14_id",
      content: "Good point. Let's discuss that in the call.",
      senderId: "user3_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:40:00Z"),
      updatedAt: new Date("2024-08-15T08:40:00Z"),
    },
    {
      id: "msg15_id",
      content: "Sounds good to me.",
      senderId: "user1_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:42:00Z"),
      updatedAt: new Date("2024-08-15T08:42:00Z"),
    },
    {
      id: "msg16_id",
      content: "See you all at 3 PM!",
      senderId: "user4_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:45:00Z"),
      updatedAt: new Date("2024-08-15T08:45:00Z"),
    },
    {
      id: "msg17_id",
      content: "Looking forward to it!",
      senderId: "user3_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T08:50:00Z"),
      updatedAt: new Date("2024-08-15T08:50:00Z"),
    },
    {
      id: "msg18_id",
      content: "Just finished another task, see you soon.",
      senderId: "user2_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T09:00:00Z"),
      updatedAt: new Date("2024-08-15T09:00:00Z"),
    },
    {
      id: "msg19_id",
      content: "Nice work, Bob!",
      senderId: "user1_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T09:05:00Z"),
      updatedAt: new Date("2024-08-15T09:05:00Z"),
    },
    {
      id: "msg20_id",
      content: "Thanks, Alice! Let's keep the momentum going.",
      senderId: "user2_id",
      chatId: "chat2_id",
      createdAt: new Date("2024-08-15T09:10:00Z"),
      updatedAt: new Date("2024-08-15T09:10:00Z"),
    },
  ],
  participants: [
    { id: "user1_id", name: "Alice" },
    { id: "user2_id", name: "Bob" },
    { id: "user3_id", name: "Charlie" },
    { id: "user4_id", name: "Diana" },
  ],
};
