import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/providers/toast-provider";
import "react-toastify/dist/ReactToastify.css";
import { UserProvider } from "@/contexts/user.context";
const roboto = Roboto({ subsets: ["latin"], weight: ["700", "400", "300"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={roboto.className}>
          {children}
          <ToastProvider />
        </body>
      </UserProvider>
    </html>
  );
}
